### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[4,0] = 10000 is not in [0, 10000)

### ISSUE THREAD

**Issue by shenGrant** [TannerGilbert/Articles#1]
Hi Gilbert,
Have u encountered this problem? i have not changed ur codes, and run it on local.
Thanks

**Comment by heisenbug601** [comment]
the same to you 

InvalidArgumentError (see above for traceback): indices[7,0] = 10000 is not in [0, 10000)

**Comment by TannerGilbert** [comment]
Sorry for not responding. Someone else also had the problem and he fixed it. I just asked him what he did and will let you know as soon as he responds.

**Comment by TannerGilbert** [comment]
Found the error. I used an wrong input_dim. It should be maximum integer index + 1 as explained in the [Keras documentation](https://keras.io/layers/embeddings/) and I just used the maximum integer index. 

Sorry for not answering earlier but it looks like this error only occurres when using a CPU and therefore it worked just fine for me. I will update the repository in a few minutes. 

Kind regards,
Gilbert Tanner

**Comment by bhansa** [comment]
Hi @TannerGilbert, 
First of all, thanks for the notebook, it's very helpful. I got the same error while trying to run the code.
Below are some details about my dataset and dimensions which I was passing. I tried to use the dot product example(method 1).
```
train.head()
```
BookID | UserID | USERRATINGS
-- | -- | --
114530 | 644108 | 4
114530 | 614998 | 4
114530 | 618764 | 4
114530 | 608366 | 4
114530 | 655265 | 4

```python
n_users = len(dataset.UserID.unique())
print(n_users) #12915

n_books = len(dataset.BookID.unique())
print(n_books) #4469

InvalidArgumentError: indices[0,0] = 114530 is not in [0, 4470)
	 [[{{node Book-Embedding_4/embedding_lookup}}]]
```
Let me know if you have any idea about this issue.

Thanks,
Bharat

**Comment by TannerGilbert** [comment]
Hello @bhansa,

This error occurres when using the false input_dim for the embedding layers. The input_dim attribute for the embedding layer in Keras is defined as follows:
- input_dim: int > 0. Size of the vocabulary, i.e. maximum integer index + 1.

Maybe you need to add 1 as indicated above. Check out [this stackoverflow post](https://stackoverflow.com/questions/54176051/invalidargumenterror-indicesi-0-x-is-not-in-0-x-in-keras) for more information.

Hope this helped.
